# This is a TOML document

instance_name = "Bob"

[group]

[group.alpha]

# LCM configuration url; see https://lcm-proj.github.io/group__LcmC__lcm__t.html#gaf29963ef43edadf45296d5ad82c18d4b
#example: "udpm://239.255.76.67:7667?ttl=1" . 
# can be empty for default
algorithm     = "AES-128/GCM"
multicast_url = "udpm://239.255.76.67:7667"
privkey       = "x509v3/bob.key"
cert          = "x509v3/bob.crt"
root_ca       = "x509v3/root_ca.crt"


[group.alpha.channel1]

channelname   = "channel1"
send          = false
receive       = true

[group.alpha.channel2]

channelname   = "channel2"
send          = false
receive       = true
